services:
  - type: web
    name: Final_BC_Predict-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn back.main:app --host 127.0.0.1 --port 8000
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: Final_BC_Predict-frontend
    env: node
    buildCommand: "npm install && npm run build"   # คำสั่งสำหรับติดตั้ง dependencies และ build
    startCommand: "serve -s build"                 # คำสั่งสำหรับรันแอปหลังจาก build เสร็จ
    staticPublishPath: "build"                     # ชี้ไปที่โฟลเดอร์ build ที่สร้างขึ้นจาก npm run build
    plan: free
    autoDeploy: true
